### ISSUE TITLE
Feature: List of packages

### ISSUE THREAD

**Issue by Silipwn** [IoT-PTv/IoT-PT#2]
I think, it would be cool to  have a list of packages and their versions that are installed in the OS. 
|  Package Name |  Version |  Link |
|---------------|----------|-------|
|  Foo             |     v1.0     |      foo.com |
|       Abc        |      v1.2    |    abc.com   |

**Comment by V33RU** [comment]
Updating here https://github.com/IoT-PTv/List-of-Tools

**Comment by Silipwn** [comment]
Alright :)
