### ISSUE TITLE
VMware

### ISSUE THREAD

**Issue by Dev-maker** [IoT-PTv/IoT-PT#4]
can you make one for VMware

**Comment by V33RU** [comment]
IoT-PT ova file will load into vmware, follow the url will give an idea

https://docs.vmware.com/en/VMware-vSphere/6.7/com.vmware.vsphere.html.hostclient.doc/GUID-8ABDB2E1-DDBF-40E3-8ED6-DC857783E3E3.html, 

all you need to do is
```bash
sudo apt-get install open-vm-tools-desktop
```
then OS will work with VMware without an issue
